name: rockbuilder_apps_builder

on:
  workflow_call:
    inputs:
      amdgpu_family:
        required: true
        type: string
      python_version:
        required: true
        type: string
      release_type:
        description: The type of release to build ("dev", "nightly", or "prerelease"). All developer-triggered jobs should use "dev"!
        required: true
        type: string
      s3_subdir:
        description: S3 subdirectory, not including the GPU-family
        required: true
        type: string
      s3_staging_subdir:
        description: S3 staging subdirectory, not including the GPU-family
        required: true
        type: string
      rocm_version:
        description: ROCm version to pip install (e.g. "7.11.0a20260121")
        type: string
      app_cfg_name:
        description: rockbuilder application to build. (for example apps/pytorch.cfg)
        required: true
        type: string
      repository:
        description: "Repository to checkout. Otherwise, defaults to `github.repository`."
        type: string
      ref:
        description: "Branch, tag or SHA to checkout. Defaults to the reference or SHA that triggered the workflow."
        type: string
  workflow_dispatch:
    inputs:
      amdgpu_family:
        type: choice
        options:
          - gfx101X-dgpu
          - gfx103X-dgpu
          - gfx110X-all
          - gfx1150
          - gfx1151
          - gfx1152
          - gfx1153
          - gfx120X-all
          - gfx90X-dcgpu
          - gfx94X-dcgpu
          - gfx950-dcgpu
        default: gfx120X-all
      python_version:
        required: true
        type: string
        default: "3.12"
      release_type:
        description: The type of release to build ("dev", "nightly", or "prerelease"). All developer-triggered jobs should use "dev"!
        type: string
        default: "dev"
      s3_subdir:
        description: S3 subdirectory, not including the GPU-family
        type: string
        default: "v2"
      s3_staging_subdir:
        description: S3 staging subdirectory, not including the GPU-family
        type: string
        default: "v2-staging"
      rocm_version:
        description: ROCm version to pip install (e.g. "7.11.0a20260121")
        type: string
        default: "7.11.0a20260121"
      app_cfg_name:
        description: rockbuilder application to build. (for example apps/pytorch.cfg)
        required: true
        type: string
        default: "apps/pytorch_29.cfg"

permissions:
  id-token: write
  contents: read

run-name: rockbuilder_apps_builder (${{ inputs.amdgpu_family }}, ${{ inputs.python_version }}, ${{ inputs.release_type }})

jobs:
  build_pytorch_wheels:
    name: Build | ${{ inputs.amdgpu_family }} | py ${{ inputs.python_version }} | ${{ inputs.app_cfg_name }}
    runs-on: ${{ github.repository_owner == 'ROCm' && 'azure-linux-scale-rocm' || 'ubuntu-24.04' }}
    container:
      image: ghcr.io/rocm/therock_build_manylinux_x86_64@sha256:6e8242d347af7e0c43c82d5031a3ac67b669f24898ea8dc2f1d5b7e4798b66bd
    env:
      OUTPUT_DIR: ${{ github.workspace }}/output
      PACKAGE_DIST_DIR: ${{ github.workspace }}/output/packages/dist
      S3_BUCKET_PY: "therock-${{ inputs.release_type }}-python"
      optional_build_prod_arguments: ""
    outputs:
      cp_version: ${{ env.cp_version }}
    steps:
      - name: checkout_rockbuilder_src
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: ${{ inputs.repository || github.repository }}
          ref: ${{ inputs.ref || '' }}

      - name: git_config
        run: |
          git config --global user.name "rockbuilder"
          git config --global user.email "rockbuilder@amd.com"

      - name: get_cp_python_base_name
        run: |
          python3 .github/build_files/get_python_cp_version.py \
            --python-version ${{ inputs.python_version }}

      - name: add_cp_python_to_path
        run: |
          python_dir="/opt/python/${{ env.cp_version }}"
          if ! [ -x "${python_dir}/bin/python" ]; then
            echo "ERROR: Could not find python: ${python_dir}"
            exit 1
          fi
          echo "python_dir: ${python_dir}"
          echo "${python_dir}/bin" >> "$GITHUB_PATH"

      - name: config_rockbuilder
        run: |
          python3 .github/build_files/generate_rockbuilder_wheel_install_cfg.py ${{ inputs.rocm_version }} ${{ inputs.amdgpu_family }} ./rockbuilder.cfg

      - name: ls_files
        run: |
          ls -la
          ls -la .github/build_files/

      - name: build_rockbuilder_app
        run: |
          source ./init_rcb_env.sh
          python3 ./rockbuilder.py ${{ inputs.app_cfg_name }}
