name: rockbuilder_apps_builder

on:
  workflow_call:
    inputs:
      amdgpu_family:
        required: true
        type: string
      python_version:
        required: true
        type: string
      release_type:
        description: The type of release to build ("dev", "nightly", or "prerelease"). All developer-triggered jobs should use "dev"!
        required: true
        type: string
      s3_subdir:
        description: S3 subdirectory, not including the GPU-family
        required: true
        type: string
      s3_staging_subdir:
        description: S3 staging subdirectory, not including the GPU-family
        required: true
        type: string
      cloudfront_url:
        description: CloudFront URL pointing to Python index
        required: true
        type: string
      cloudfront_staging_url:
        description: CloudFront base URL pointing to staging Python index
        required: true
        type: string
      rocm_version:
        description: ROCm version to pip install (e.g. "7.10.0a20251124")
        type: string
      apps_file_name:
        description: PyTorch ref to checkout. (typically "nightly", or "release/X.Y")
        required: true
        type: string
      repository:
        description: "Repository to checkout. Otherwise, defaults to `github.repository`."
        type: string
      ref:
        description: "Branch, tag or SHA to checkout. Defaults to the reference or SHA that triggered the workflow."
        type: string
  workflow_dispatch:
    inputs:
      amdgpu_family:
        type: choice
        options:
          - gfx101X-dgpu
          - gfx103X-dgpu
          - gfx110X-all
          - gfx1150
          - gfx1151
          - gfx1152
          - gfx1153
          - gfx120X-all
          - gfx90X-dcgpu
          - gfx94X-dcgpu
          - gfx950-dcgpu
        default: gfx120X-all
      python_version:
        required: true
        type: string
        default: "3.12"
      release_type:
        description: The type of release to build ("dev", "nightly", or "prerelease"). All developer-triggered jobs should use "dev"!
        type: string
        default: "dev"
      s3_subdir:
        description: S3 subdirectory, not including the GPU-family
        type: string
        default: "v2"
      s3_staging_subdir:
        description: S3 staging subdirectory, not including the GPU-family
        type: string
        default: "v2-staging"
      cloudfront_url:
        description: CloudFront base URL pointing to Python index
        type: string
        default: "https://rocm.devreleases.amd.com/v2"
      cloudfront_staging_url:
        description: CloudFront base URL pointing to staging Python index
        type: string
        default: "https://rocm.devreleases.amd.com/v2-staging"
      rocm_version:
        description: ROCm version to pip install (e.g. "7.10.0a20251124")
        type: string
        default: "7.11.0a20260121"
      apps_file_name:
        description: PyTorch ref to checkout. (typically "nightly", or "release/X.Y")
        required: true
        type: string
        default: "apps/pytorch_29.cfg"

permissions:
  id-token: write
  contents: read

run-name: Build portable Linux PyTorch Wheels (${{ inputs.amdgpu_family }}, ${{ inputs.python_version }}, ${{ inputs.release_type }})

jobs:
  build_pytorch_wheels:
    name: Build | ${{ inputs.amdgpu_family }} | py ${{ inputs.python_version }} | ${{ inputs.apps_file_name }}
    runs-on: ${{ github.repository_owner == 'ROCm' && 'azure-linux-scale-rocm' || 'ubuntu-24.04' }}
    container:
      image: ghcr.io/rocm/therock_build_manylinux_x86_64@sha256:6e8242d347af7e0c43c82d5031a3ac67b669f24898ea8dc2f1d5b7e4798b66bd
    env:
      OUTPUT_DIR: ${{ github.workspace }}/output
      PACKAGE_DIST_DIR: ${{ github.workspace }}/output/packages/dist
      S3_BUCKET_PY: "therock-${{ inputs.release_type }}-python"
      optional_build_prod_arguments: ""
    outputs:
      cp_version: ${{ env.cp_version }}
      # The following are python package versions produced by the build. The
      # exact versions will depend on workflow inputs and the underlying code.
      # For example:
      #   Inputs
      #     rocm_version       : 7.10.0a20251120
      #     pytorch_git_ref    : release/2.9
      #   Outputs
      #     torch_version      : 2.9.1+rocm7.10.0a20251120
      #     torchaudio_version : 2.9.0+rocm7.10.0a20251120
      #     torchvision_version: 0.24.0+rocm7.10.0a20251120
      #     triton_version     : 3.5.1+rocm7.10.0a20251120
      # Future jobs can use these version outputs to identify newly built
      # packages, for example via `pip install torch==${TORCH_VERSION}`.
      torch_version: ${{ steps.build-pytorch-wheels.outputs.torch_version }}
      torchaudio_version: ${{ steps.build-pytorch-wheels.outputs.torchaudio_version }}
      torchvision_version: ${{ steps.build-pytorch-wheels.outputs.torchvision_version }}
      triton_version: ${{ steps.build-pytorch-wheels.outputs.triton_version }}
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: ${{ inputs.repository || github.repository }}
          ref: ${{ inputs.ref || '' }}

      - name: git config
        run: |
          git config --global user.name "rockbuilder"
          git config --global user.email "rockbuilder@amd.com"

      - name: Select Python version
        run: |
          python .github/build_files/get_python_cp_version.py \
            --python-version ${{ inputs.python_version }}

      - name: Add selected Python version to PATH
        run: |
          python_dir="/opt/python/${{ env.cp_version }}"
          if ! [ -x "${python_dir}/bin/python" ]; then
            echo "ERROR: Could not find python: ${python_dir}"
            exit 1
          fi
          echo "python_dir: ${python_dir}"
          echo "${python_dir}/bin" >> "$GITHUB_PATH"
